Update TS Config to support new decorators model definition
sequelize/sequelize-sscce pull request #272
Opened 2024-02-13 17:10 UTC by johneatmon

Redo of #267:

Based on [this issue](https://github.com/sequelize/website/issues/552) and [this issue](https://github.com/sequelize/sequelize/issues/16866).

Update `tsconfig.json`:
- Add support for `experimentalDecorators`
- Bump module and moduleResolution to import `@sequelize/core/decorators-legacy` declarations properly

Update `sscce-sequelize-7.ts`:
- Add new Bar model to demonstrate new model definition example with decorators

2024-02-18 00:23 UTC, ephys requested changes
small change request, but otherwise good! :)

2024-02-18 00:23 UTC, ephys commented on src/sscce-sequelize-7.ts
> +  class Bar extends Model {
considering this is the recommended way of using Sequelize 7, I would make this a replacement of Foo instead

Note that you don't need the decorators for the primary key attribute, only the type definition, as it's automatically added

You also need the two generics

```suggestion
  class Bar extends Model<InferAttributes<Bar>, InferCreationAttributes<Bar>> {
```

2024-02-19 21:57 UTC, johneatmon commented
_Voilà_

2024-03-25 09:12 UTC, ephys approved these changes
Thank you!

2024-03-25 09:12 UTC, merged

2025-04-04 19:44 UTC, yharishy commented
When is this change will be available in sequelize/core ?